"""add subscription column on user table

Revision ID: fe5651aa191f
Revises: 0592b3295882
Create Date: 2018-10-22 10:50:04.308583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5651aa191f'
down_revision = '0592b3295882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
